### PR TITLE
SR NOR

### PR DESCRIPTION
**Pull request by mpeychich**
Updated to only update outputs when input is changed low to high.

### CODE REVIEW

**Comment by eisental** [comment]
Ok, my first git merge. The srnor is now part of the package. 
One question though, when the input changes, you first set all the bits to on and only then sets one off. Do you need another circuit to see that it's on before it turns off?

**Comment by eisental** [comment]
It would be great if you can write a doc page and either send me the text or make a pull request on github.com/eisental/RedstoneChips branch gh-pages. Making the pull request might be too much effort, but its a nice way to make changes to the site and i would be interested to see if it works.

**Comment by mpeychich** [comment]
well, with just 2 inputs and 2 outputs, this is a strict SR NOR.  Once you add a third pair, you get some bonus logic action.  Lets say we wanted to do 4 set pins in pure redstone.  We would need 4 SR NORs with all 4 set pins ORd together and forwarded to all 4 reset pins. Using this SR NOR circuit, we are giving the user the OR logic for free after 2 inputs.  If the user wants to use pure SR NOR, they can create multiple 2in/2out circuits and do the ORing themselves.  The reason I first turn all outputs to high and then one output to low is to account for n inputs and outputs.

**Comment by mpeychich** [comment]
Okay, I'll go the pull request route on the docs.

**Comment by eisental** [comment]
I'm just troubled about the fact that theres one extra setData operation on each input change. each sendOutput() call actually moves the lever so I think I'll make a change so it's only written once.

**Comment by mpeychich** [comment]
Appreciated.  I didn't even know sendOutput() caused the levers to move.

**Pull request merged**
